name: Client_Push Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./YuYuWechatV2_Client

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: image=moby/buildkit:buildx-stable-1

    - name: Build Docker image
      run: docker build -t my-python-app .

    - name: Run Docker container
      run: docker run -d -p 7000:7000 --name my-python-app-container my-python-app

    - name: Wait for the server to start
      run: sleep 10

    - name: Display Docker logs
      run: docker logs my-python-app-container

    - name: Test main endpoint
      run: curl --fail http://127.0.0.1:7000

    - name: Test admin endpoint
      run: curl --fail http://127.0.0.1:7000/admin

    - name: Test send_message_management endpoint
      run: curl --fail http://127.0.0.1:7000/send_message_management/

    - name: Test schedule_management endpoint
      run: curl --fail http://127.0.0.1:7000/schedule_management/

    - name: Stop and remove Docker container
      run: docker rm -f my-python-app-container

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./YuYuWechatV2_Client
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/yuyuwechatv2_client:latest
        platforms: linux/amd64,linux/arm64