name: server_Compile with PyInstaller

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./YuYuWechatV2_Server
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Compile with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller YuYuWechatV2_Server.spec