name: server Test When commit

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./YuYuWechatV2_Server
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start server
      run: |
        Start-Process -NoNewWindow -FilePath 'python' -ArgumentList 'manage.py runserver 0.0.0.0:8000'
        sleep 8
    - name: Ping server
      run: |
        curl  http://localhost:8000/wechat/ping/