name: server_Test When commit.yml

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./YuYuWechatV2_Server
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start server
      shell: pwsh
      run: |
        Start-Process -FilePath "python" -ArgumentList "manage.py runserver 0.0.0.0:8000" -NoNewWindow
        Start-Sleep -Seconds 10
    - name: Test server
      run: |
        curl http://127.0.0.1:8000/wechat/ping